/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rogueone.traincon.gui;

import com.rogueone.traincon.TrainController;

/**
 *
 * @author kylemonto
 */
public class TrainControllerGUI extends javax.swing.JPanel {

    /**
     * Creates new form TrainControllerGUI
     */
    public TrainControllerGUI() {
        initComponents();
    }

    public TrainControllerGUI(TrainController trainControllerObject) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACGroup = new javax.swing.ButtonGroup();
        LightsGroup = new javax.swing.ButtonGroup();
        RightDoorGroup = new javax.swing.ButtonGroup();
        LeftDoorGroup = new javax.swing.ButtonGroup();
        HeatGroup = new javax.swing.ButtonGroup();
        ModeGroup = new javax.swing.ButtonGroup();
        TrainControlsPanel = new javax.swing.JPanel();
        ControlsAC = new javax.swing.JPanel();
        ACOn = new javax.swing.JRadioButton();
        ACOff = new javax.swing.JRadioButton();
        ControlsLights = new javax.swing.JPanel();
        LightsOn = new javax.swing.JRadioButton();
        LightsOff = new javax.swing.JRadioButton();
        ControlsLeftDoor = new javax.swing.JPanel();
        LeftDoorOpened = new javax.swing.JRadioButton();
        LeftDoorClosed = new javax.swing.JRadioButton();
        ControlsRightDoor = new javax.swing.JPanel();
        ControlsRightDoorClosed = new javax.swing.JRadioButton();
        ControlsRightDoorOpened = new javax.swing.JRadioButton();
        SpeedInput = new javax.swing.JSpinner();
        SetSpeed = new javax.swing.JButton();
        ControlsSystemMode = new javax.swing.JPanel();
        ManualModeSelect = new javax.swing.JRadioButton();
        AutoModeSelect = new javax.swing.JRadioButton();
        ControlMPHLabel = new javax.swing.JLabel();
        AnnouncementText = new javax.swing.JTextField();
        SendAnnouncement = new javax.swing.JButton();
        KpInput = new javax.swing.JSpinner();
        KpLabel = new javax.swing.JLabel();
        SetKp = new javax.swing.JButton();
        KiInput = new javax.swing.JSpinner();
        KiLabel = new javax.swing.JLabel();
        SetKi = new javax.swing.JButton();
        ControlsHeat = new javax.swing.JPanel();
        HeatOn = new javax.swing.JRadioButton();
        HeatOff = new javax.swing.JRadioButton();
        Status = new javax.swing.JPanel();
        StatusHeat = new javax.swing.JPanel();
        StatusHeatImage = new javax.swing.JLabel();
        PowerStatusLabel = new javax.swing.JLabel();
        StatusLights = new javax.swing.JPanel();
        StatusLightsImage = new javax.swing.JLabel();
        AntennaStatusLabel = new javax.swing.JLabel();
        StatusLights1 = new javax.swing.JPanel();
        StatusLightsImage1 = new javax.swing.JLabel();
        BrakeStatusLabel = new javax.swing.JLabel();
        EmergencyBrakeToggleButton = new javax.swing.JToggleButton();
        TrainInformation = new javax.swing.JPanel();
        TrainInfoScrollPane = new javax.swing.JScrollPane();
        TrainInfoText = new javax.swing.JTextArea();
        TrainSelectorDropDown = new javax.swing.JComboBox<>();
        RealTimeHUD = new javax.swing.JPanel();
        RealTimeSpeedAndAuthority = new javax.swing.JPanel();
        ActualSpeedPanel = new javax.swing.JPanel();
        ActualSpeedUnitsLabel = new javax.swing.JLabel();
        ActualSpeedLabel = new javax.swing.JLabel();
        SpeedLimitPanel = new javax.swing.JPanel();
        SpeedLimitUnitsLabel = new javax.swing.JLabel();
        SpeedLimitLabel = new javax.swing.JLabel();
        AuthorityPanel = new javax.swing.JPanel();
        AuthorityUnitsLabel = new javax.swing.JLabel();
        AuthorityLabel = new javax.swing.JLabel();
        RealTimePower = new javax.swing.JPanel();
        MaxPowerPanel = new javax.swing.JPanel();
        MaxPowerUnitsLabel = new javax.swing.JLabel();
        MaxPowerLabel = new javax.swing.JLabel();
        PowerUsedPanel = new javax.swing.JPanel();
        PowerUnitsLabel = new javax.swing.JLabel();
        PowerUsedLabel = new javax.swing.JLabel();
        RealTimeNotifications = new javax.swing.JPanel();
        RealTimeNotificationsText = new javax.swing.JScrollPane();
        NotificationsDisplay = new javax.swing.JTextArea();
        Clock = new javax.swing.JPanel();
        ClockScrollPane = new javax.swing.JScrollPane();
        ClockText = new javax.swing.JTextArea();
        ServiceBrakeToggleButton = new javax.swing.JToggleButton();
        FailureSimulationPanel = new javax.swing.JPanel();
        ServiceBrakeFailureCheck = new javax.swing.JCheckBox();
        PowerFailureCheck = new javax.swing.JCheckBox();
        AntennaFailureCheck = new javax.swing.JCheckBox();
        TrainSelectorButton = new javax.swing.JButton();

        TrainControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Train Controls"));

        ControlsAC.setBorder(javax.swing.BorderFactory.createTitledBorder("A/C"));

        ACGroup.add(ACOn);
        ACOn.setText("On");

        ACGroup.add(ACOff);
        ACOff.setSelected(true);
        ACOff.setText("Off");

        javax.swing.GroupLayout ControlsACLayout = new javax.swing.GroupLayout(ControlsAC);
        ControlsAC.setLayout(ControlsACLayout);
        ControlsACLayout.setHorizontalGroup(
            ControlsACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsACLayout.createSequentialGroup()
                .addComponent(ACOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACOff)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlsACLayout.setVerticalGroup(
            ControlsACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ACOn)
                .addComponent(ACOff))
        );

        ControlsLights.setBorder(javax.swing.BorderFactory.createTitledBorder("Lights"));

        LightsGroup.add(LightsOn);
        LightsOn.setText("On");

        LightsGroup.add(LightsOff);
        LightsOff.setSelected(true);
        LightsOff.setText("Off");

        javax.swing.GroupLayout ControlsLightsLayout = new javax.swing.GroupLayout(ControlsLights);
        ControlsLights.setLayout(ControlsLightsLayout);
        ControlsLightsLayout.setHorizontalGroup(
            ControlsLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsLightsLayout.createSequentialGroup()
                .addComponent(LightsOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LightsOff)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlsLightsLayout.setVerticalGroup(
            ControlsLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LightsOn)
                .addComponent(LightsOff))
        );

        ControlsLeftDoor.setBorder(javax.swing.BorderFactory.createTitledBorder("Left Door"));

        LeftDoorGroup.add(LeftDoorOpened);
        LeftDoorOpened.setText("Opened");

        LeftDoorGroup.add(LeftDoorClosed);
        LeftDoorClosed.setSelected(true);
        LeftDoorClosed.setText("Closed");

        javax.swing.GroupLayout ControlsLeftDoorLayout = new javax.swing.GroupLayout(ControlsLeftDoor);
        ControlsLeftDoor.setLayout(ControlsLeftDoorLayout);
        ControlsLeftDoorLayout.setHorizontalGroup(
            ControlsLeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsLeftDoorLayout.createSequentialGroup()
                .addComponent(LeftDoorOpened)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeftDoorClosed)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlsLeftDoorLayout.setVerticalGroup(
            ControlsLeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsLeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LeftDoorOpened)
                .addComponent(LeftDoorClosed))
        );

        ControlsRightDoor.setBorder(javax.swing.BorderFactory.createTitledBorder("Right Door"));

        RightDoorGroup.add(ControlsRightDoorClosed);
        ControlsRightDoorClosed.setSelected(true);
        ControlsRightDoorClosed.setText("Closed");

        RightDoorGroup.add(ControlsRightDoorOpened);
        ControlsRightDoorOpened.setText("Opened");

        javax.swing.GroupLayout ControlsRightDoorLayout = new javax.swing.GroupLayout(ControlsRightDoor);
        ControlsRightDoor.setLayout(ControlsRightDoorLayout);
        ControlsRightDoorLayout.setHorizontalGroup(
            ControlsRightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsRightDoorLayout.createSequentialGroup()
                .addComponent(ControlsRightDoorOpened)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsRightDoorClosed)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlsRightDoorLayout.setVerticalGroup(
            ControlsRightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsRightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ControlsRightDoorOpened)
                .addComponent(ControlsRightDoorClosed))
        );

        SetSpeed.setText("Set Speed");

        ControlsSystemMode.setBorder(javax.swing.BorderFactory.createTitledBorder("System Mode"));

        ModeGroup.add(ManualModeSelect);
        ManualModeSelect.setText("Manual");

        ModeGroup.add(AutoModeSelect);
        AutoModeSelect.setSelected(true);
        AutoModeSelect.setText("Automatic");

        javax.swing.GroupLayout ControlsSystemModeLayout = new javax.swing.GroupLayout(ControlsSystemMode);
        ControlsSystemMode.setLayout(ControlsSystemModeLayout);
        ControlsSystemModeLayout.setHorizontalGroup(
            ControlsSystemModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsSystemModeLayout.createSequentialGroup()
                .addComponent(ManualModeSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AutoModeSelect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlsSystemModeLayout.setVerticalGroup(
            ControlsSystemModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsSystemModeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlsSystemModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualModeSelect)
                    .addComponent(AutoModeSelect)))
        );

        ControlMPHLabel.setText("mph");

        AnnouncementText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnnouncementText.setText("Type Announcement Here...");

        SendAnnouncement.setText("Make Announcement");

        KpLabel.setText("Kp");

        SetKp.setText("Set Kp");
        SetKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetKpActionPerformed(evt);
            }
        });

        KiLabel.setText("Ki");

        SetKi.setText("Set Ki");
        SetKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetKiActionPerformed(evt);
            }
        });

        ControlsHeat.setBorder(javax.swing.BorderFactory.createTitledBorder("Heat"));

        HeatGroup.add(HeatOn);
        HeatOn.setText("On");

        HeatGroup.add(HeatOff);
        HeatOff.setSelected(true);
        HeatOff.setText("Off");

        javax.swing.GroupLayout ControlsHeatLayout = new javax.swing.GroupLayout(ControlsHeat);
        ControlsHeat.setLayout(ControlsHeatLayout);
        ControlsHeatLayout.setHorizontalGroup(
            ControlsHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsHeatLayout.createSequentialGroup()
                .addComponent(HeatOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HeatOff)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlsHeatLayout.setVerticalGroup(
            ControlsHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(HeatOn)
                .addComponent(HeatOff))
        );

        javax.swing.GroupLayout TrainControlsPanelLayout = new javax.swing.GroupLayout(TrainControlsPanel);
        TrainControlsPanel.setLayout(TrainControlsPanelLayout);
        TrainControlsPanelLayout.setHorizontalGroup(
            TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlsAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ControlsLights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ControlsLeftDoor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ControlsRightDoor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ControlsSystemMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ControlsHeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SendAnnouncement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AnnouncementText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                        .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                                .addComponent(KiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KiLabel))
                            .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                                .addComponent(KpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KpLabel))
                            .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                                .addComponent(SpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ControlMPHLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SetKp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SetSpeed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SetKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TrainControlsPanelLayout.setVerticalGroup(
            TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainControlsPanelLayout.createSequentialGroup()
                .addComponent(ControlsSystemMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetSpeed)
                    .addComponent(ControlMPHLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetKp)
                    .addComponent(KpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrainControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetKi)
                    .addComponent(KiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnouncementText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendAnnouncement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ControlsHeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsLights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsLeftDoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlsRightDoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Status.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        StatusHeat.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));

        StatusHeatImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusHeatImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rogueone/images/CIRC_98.png"))); // NOI18N
        StatusHeatImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PowerStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PowerStatusLabel.setText("ACTIVE");

        javax.swing.GroupLayout StatusHeatLayout = new javax.swing.GroupLayout(StatusHeat);
        StatusHeat.setLayout(StatusHeatLayout);
        StatusHeatLayout.setHorizontalGroup(
            StatusHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusHeatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PowerStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(StatusHeatLayout.createSequentialGroup()
                        .addComponent(StatusHeatImage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        StatusHeatLayout.setVerticalGroup(
            StatusHeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusHeatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusHeatImage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PowerStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatusLights.setBorder(javax.swing.BorderFactory.createTitledBorder("Antenna"));
        StatusLights.setPreferredSize(new java.awt.Dimension(140, 190));

        StatusLightsImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLightsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rogueone/images/CIRC_98.png"))); // NOI18N
        StatusLightsImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AntennaStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AntennaStatusLabel.setText("ACTIVE");

        javax.swing.GroupLayout StatusLightsLayout = new javax.swing.GroupLayout(StatusLights);
        StatusLights.setLayout(StatusLightsLayout);
        StatusLightsLayout.setHorizontalGroup(
            StatusLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLightsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLightsLayout.createSequentialGroup()
                        .addComponent(StatusLightsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AntennaStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatusLightsLayout.setVerticalGroup(
            StatusLightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLightsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StatusLightsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AntennaStatusLabel)
                .addGap(31, 31, 31))
        );

        StatusLights1.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Brake"));
        StatusLights1.setPreferredSize(new java.awt.Dimension(140, 190));

        StatusLightsImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLightsImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rogueone/images/CIRC_98.png"))); // NOI18N
        StatusLightsImage1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BrakeStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BrakeStatusLabel.setText("ACTIVE");

        javax.swing.GroupLayout StatusLights1Layout = new javax.swing.GroupLayout(StatusLights1);
        StatusLights1.setLayout(StatusLights1Layout);
        StatusLights1Layout.setHorizontalGroup(
            StatusLights1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLights1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLights1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLights1Layout.createSequentialGroup()
                        .addComponent(StatusLightsImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BrakeStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatusLights1Layout.setVerticalGroup(
            StatusLights1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLights1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StatusLightsImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrakeStatusLabel)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusHeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(StatusLights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(StatusLights1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusLights, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
            .addComponent(StatusHeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StatusLights1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        EmergencyBrakeToggleButton.setText("Emergency Brake");

        TrainInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Train Information"));

        TrainInfoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TrainInfoScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TrainInfoText.setColumns(20);
        TrainInfoText.setRows(5);
        TrainInfoText.setText("Train ID:\nLine:\nSection:\nBlock:\nPassengers:\nTemp:\n\n");
        TrainInfoScrollPane.setViewportView(TrainInfoText);

        javax.swing.GroupLayout TrainInformationLayout = new javax.swing.GroupLayout(TrainInformation);
        TrainInformation.setLayout(TrainInformationLayout);
        TrainInformationLayout.setHorizontalGroup(
            TrainInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        TrainInformationLayout.setVerticalGroup(
            TrainInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        TrainSelectorDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RealTimeHUD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Real Time HUD"));

        RealTimeSpeedAndAuthority.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed and Authority"));

        ActualSpeedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Actual Speed"));

        ActualSpeedUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ActualSpeedUnitsLabel.setText("mph");

        ActualSpeedLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ActualSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ActualSpeedLabel.setText("55");

        javax.swing.GroupLayout ActualSpeedPanelLayout = new javax.swing.GroupLayout(ActualSpeedPanel);
        ActualSpeedPanel.setLayout(ActualSpeedPanelLayout);
        ActualSpeedPanelLayout.setHorizontalGroup(
            ActualSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualSpeedPanelLayout.createSequentialGroup()
                .addComponent(ActualSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualSpeedUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ActualSpeedPanelLayout.setVerticalGroup(
            ActualSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActualSpeedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualSpeedUnitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SpeedLimitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed Limit"));

        SpeedLimitUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SpeedLimitUnitsLabel.setText("mph");

        SpeedLimitLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SpeedLimitLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SpeedLimitLabel.setText("55");

        javax.swing.GroupLayout SpeedLimitPanelLayout = new javax.swing.GroupLayout(SpeedLimitPanel);
        SpeedLimitPanel.setLayout(SpeedLimitPanelLayout);
        SpeedLimitPanelLayout.setHorizontalGroup(
            SpeedLimitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeedLimitPanelLayout.createSequentialGroup()
                .addComponent(SpeedLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpeedLimitUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SpeedLimitPanelLayout.setVerticalGroup(
            SpeedLimitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpeedLimitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SpeedLimitUnitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AuthorityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Authority"));

        AuthorityUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AuthorityUnitsLabel.setText("feet");

        AuthorityLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AuthorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AuthorityLabel.setText("300");

        javax.swing.GroupLayout AuthorityPanelLayout = new javax.swing.GroupLayout(AuthorityPanel);
        AuthorityPanel.setLayout(AuthorityPanelLayout);
        AuthorityPanelLayout.setHorizontalGroup(
            AuthorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorityPanelLayout.createSequentialGroup()
                .addComponent(AuthorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AuthorityUnitsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AuthorityPanelLayout.setVerticalGroup(
            AuthorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorityPanelLayout.createSequentialGroup()
                .addGroup(AuthorityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AuthorityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(AuthorityUnitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RealTimeSpeedAndAuthorityLayout = new javax.swing.GroupLayout(RealTimeSpeedAndAuthority);
        RealTimeSpeedAndAuthority.setLayout(RealTimeSpeedAndAuthorityLayout);
        RealTimeSpeedAndAuthorityLayout.setHorizontalGroup(
            RealTimeSpeedAndAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeSpeedAndAuthorityLayout.createSequentialGroup()
                .addComponent(ActualSpeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpeedLimitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AuthorityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RealTimeSpeedAndAuthorityLayout.setVerticalGroup(
            RealTimeSpeedAndAuthorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpeedLimitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AuthorityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualSpeedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RealTimePower.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));

        MaxPowerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Maximum Power"));

        MaxPowerUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MaxPowerUnitsLabel.setText("W");

        MaxPowerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MaxPowerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MaxPowerLabel.setText("55");

        javax.swing.GroupLayout MaxPowerPanelLayout = new javax.swing.GroupLayout(MaxPowerPanel);
        MaxPowerPanel.setLayout(MaxPowerPanelLayout);
        MaxPowerPanelLayout.setHorizontalGroup(
            MaxPowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaxPowerPanelLayout.createSequentialGroup()
                .addComponent(MaxPowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaxPowerUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MaxPowerPanelLayout.setVerticalGroup(
            MaxPowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MaxPowerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MaxPowerUnitsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PowerUsedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Power Utilization"));

        PowerUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PowerUnitsLabel.setText("W");

        PowerUsedLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        PowerUsedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PowerUsedLabel.setText("55");

        javax.swing.GroupLayout PowerUsedPanelLayout = new javax.swing.GroupLayout(PowerUsedPanel);
        PowerUsedPanel.setLayout(PowerUsedPanelLayout);
        PowerUsedPanelLayout.setHorizontalGroup(
            PowerUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerUsedPanelLayout.createSequentialGroup()
                .addComponent(PowerUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PowerUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PowerUsedPanelLayout.setVerticalGroup(
            PowerUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PowerUsedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PowerUnitsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RealTimePowerLayout = new javax.swing.GroupLayout(RealTimePower);
        RealTimePower.setLayout(RealTimePowerLayout);
        RealTimePowerLayout.setHorizontalGroup(
            RealTimePowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RealTimePowerLayout.createSequentialGroup()
                .addComponent(PowerUsedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaxPowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RealTimePowerLayout.setVerticalGroup(
            RealTimePowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PowerUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MaxPowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RealTimeNotifications.setBorder(javax.swing.BorderFactory.createTitledBorder("Notifications"));

        NotificationsDisplay.setColumns(20);
        NotificationsDisplay.setRows(5);
        RealTimeNotificationsText.setViewportView(NotificationsDisplay);

        javax.swing.GroupLayout RealTimeNotificationsLayout = new javax.swing.GroupLayout(RealTimeNotifications);
        RealTimeNotifications.setLayout(RealTimeNotificationsLayout);
        RealTimeNotificationsLayout.setHorizontalGroup(
            RealTimeNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RealTimeNotificationsText)
        );
        RealTimeNotificationsLayout.setVerticalGroup(
            RealTimeNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RealTimeNotificationsText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout RealTimeHUDLayout = new javax.swing.GroupLayout(RealTimeHUD);
        RealTimeHUD.setLayout(RealTimeHUDLayout);
        RealTimeHUDLayout.setHorizontalGroup(
            RealTimeHUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RealTimeHUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RealTimeHUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RealTimeNotifications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RealTimeSpeedAndAuthority, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RealTimePower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RealTimeHUDLayout.setVerticalGroup(
            RealTimeHUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeHUDLayout.createSequentialGroup()
                .addComponent(RealTimeSpeedAndAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RealTimePower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RealTimeNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Clock.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));

        ClockScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ClockScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ClockText.setColumns(20);
        ClockText.setRows(5);
        ClockText.setText("Time and Date");
        ClockScrollPane.setViewportView(ClockText);

        javax.swing.GroupLayout ClockLayout = new javax.swing.GroupLayout(Clock);
        Clock.setLayout(ClockLayout);
        ClockLayout.setHorizontalGroup(
            ClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClockLayout.createSequentialGroup()
                .addComponent(ClockScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ClockLayout.setVerticalGroup(
            ClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClockScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        ServiceBrakeToggleButton.setText("Service Brake");
        ServiceBrakeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceBrakeToggleButtonActionPerformed(evt);
            }
        });

        FailureSimulationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Failure Simulation"));

        ServiceBrakeFailureCheck.setText("Service Brake");

        PowerFailureCheck.setText("Power");

        AntennaFailureCheck.setText("Antenna");

        javax.swing.GroupLayout FailureSimulationPanelLayout = new javax.swing.GroupLayout(FailureSimulationPanel);
        FailureSimulationPanel.setLayout(FailureSimulationPanelLayout);
        FailureSimulationPanelLayout.setHorizontalGroup(
            FailureSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FailureSimulationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FailureSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ServiceBrakeFailureCheck)
                    .addComponent(PowerFailureCheck)
                    .addComponent(AntennaFailureCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FailureSimulationPanelLayout.setVerticalGroup(
            FailureSimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FailureSimulationPanelLayout.createSequentialGroup()
                .addComponent(PowerFailureCheck)
                .addGap(18, 18, 18)
                .addComponent(AntennaFailureCheck)
                .addGap(18, 18, 18)
                .addComponent(ServiceBrakeFailureCheck)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TrainSelectorButton.setText("Show");
        TrainSelectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainSelectorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ServiceBrakeToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrainInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmergencyBrakeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FailureSimulationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TrainSelectorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrainSelectorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RealTimeHUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Clock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RealTimeHUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrainSelectorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrainSelectorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrainInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ServiceBrakeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmergencyBrakeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FailureSimulationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TrainControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ServiceBrakeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceBrakeToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceBrakeToggleButtonActionPerformed

    private void SetKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetKpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetKpActionPerformed

    private void SetKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetKiActionPerformed

    private void TrainSelectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainSelectorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainSelectorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup ACGroup;
    public javax.swing.JRadioButton ACOff;
    public javax.swing.JRadioButton ACOn;
    public javax.swing.JLabel ActualSpeedLabel;
    private javax.swing.JPanel ActualSpeedPanel;
    private javax.swing.JLabel ActualSpeedUnitsLabel;
    public javax.swing.JTextField AnnouncementText;
    public javax.swing.JCheckBox AntennaFailureCheck;
    public javax.swing.JLabel AntennaStatusLabel;
    public javax.swing.JLabel AuthorityLabel;
    private javax.swing.JPanel AuthorityPanel;
    private javax.swing.JLabel AuthorityUnitsLabel;
    public javax.swing.JRadioButton AutoModeSelect;
    public javax.swing.JLabel BrakeStatusLabel;
    private javax.swing.JPanel Clock;
    private javax.swing.JScrollPane ClockScrollPane;
    public javax.swing.JTextArea ClockText;
    private javax.swing.JLabel ControlMPHLabel;
    private javax.swing.JPanel ControlsAC;
    private javax.swing.JPanel ControlsHeat;
    private javax.swing.JPanel ControlsLeftDoor;
    private javax.swing.JPanel ControlsLights;
    private javax.swing.JPanel ControlsRightDoor;
    public javax.swing.JRadioButton ControlsRightDoorClosed;
    public javax.swing.JRadioButton ControlsRightDoorOpened;
    private javax.swing.JPanel ControlsSystemMode;
    public javax.swing.JToggleButton EmergencyBrakeToggleButton;
    private javax.swing.JPanel FailureSimulationPanel;
    private javax.swing.ButtonGroup HeatGroup;
    public javax.swing.JRadioButton HeatOff;
    public javax.swing.JRadioButton HeatOn;
    public javax.swing.JSpinner KiInput;
    private javax.swing.JLabel KiLabel;
    public javax.swing.JSpinner KpInput;
    private javax.swing.JLabel KpLabel;
    public javax.swing.JRadioButton LeftDoorClosed;
    public javax.swing.ButtonGroup LeftDoorGroup;
    public javax.swing.JRadioButton LeftDoorOpened;
    public javax.swing.ButtonGroup LightsGroup;
    public javax.swing.JRadioButton LightsOff;
    public javax.swing.JRadioButton LightsOn;
    public javax.swing.JRadioButton ManualModeSelect;
    public javax.swing.JLabel MaxPowerLabel;
    private javax.swing.JPanel MaxPowerPanel;
    private javax.swing.JLabel MaxPowerUnitsLabel;
    private javax.swing.ButtonGroup ModeGroup;
    public javax.swing.JTextArea NotificationsDisplay;
    public javax.swing.JCheckBox PowerFailureCheck;
    public javax.swing.JLabel PowerStatusLabel;
    private javax.swing.JLabel PowerUnitsLabel;
    public javax.swing.JLabel PowerUsedLabel;
    private javax.swing.JPanel PowerUsedPanel;
    private javax.swing.JPanel RealTimeHUD;
    private javax.swing.JPanel RealTimeNotifications;
    private javax.swing.JScrollPane RealTimeNotificationsText;
    private javax.swing.JPanel RealTimePower;
    private javax.swing.JPanel RealTimeSpeedAndAuthority;
    public javax.swing.ButtonGroup RightDoorGroup;
    private javax.swing.JButton SendAnnouncement;
    public javax.swing.JCheckBox ServiceBrakeFailureCheck;
    public javax.swing.JToggleButton ServiceBrakeToggleButton;
    private javax.swing.JButton SetKi;
    private javax.swing.JButton SetKp;
    private javax.swing.JButton SetSpeed;
    public javax.swing.JSpinner SpeedInput;
    public javax.swing.JLabel SpeedLimitLabel;
    private javax.swing.JPanel SpeedLimitPanel;
    private javax.swing.JLabel SpeedLimitUnitsLabel;
    private javax.swing.JPanel Status;
    private javax.swing.JPanel StatusHeat;
    public javax.swing.JLabel StatusHeatImage;
    private javax.swing.JPanel StatusLights;
    private javax.swing.JPanel StatusLights1;
    public javax.swing.JLabel StatusLightsImage;
    public javax.swing.JLabel StatusLightsImage1;
    private javax.swing.JPanel TrainControlsPanel;
    private javax.swing.JScrollPane TrainInfoScrollPane;
    public javax.swing.JTextArea TrainInfoText;
    private javax.swing.JPanel TrainInformation;
    private javax.swing.JButton TrainSelectorButton;
    private javax.swing.JComboBox<String> TrainSelectorDropDown;
    // End of variables declaration//GEN-END:variables
}
