/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rogueone.ctc.gui;
import java.awt.*;
import java.awt.event.*;
import java.text.*;
import java.util.*;
import javax.swing.*;


/**
 *
 * @author kylemonto
 */
public class CommandTrackControlGUI extends javax.swing.JPanel {
    
    int trainID;
    
    /**
     * Creates new form CommandTrackControlGUI
     */
    public CommandTrackControlGUI() {
        initComponents();
        InitializeGUIObject();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        MapPanel2 = new javax.swing.JPanel();
        MapImage2 = new javax.swing.JLabel();
        BrowserPanel2 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        TrainLineSelect2 = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TrainTable = new javax.swing.JTable();
        ChangeParametersButton3 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        TrainLineBlockSelect = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        BlockTable = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        FailureTable = new javax.swing.JTable();
        InformationPanel2 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        InformationHeader2 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        TrainSpeedLabel2 = new javax.swing.JLabel();
        TrainAuthorityLabel2 = new javax.swing.JLabel();
        TrainNameField = new javax.swing.JTextField();
        CurrentLineField = new javax.swing.JTextField();
        CurrentBlockField = new javax.swing.JTextField();
        CurrentSectionField = new javax.swing.JTextField();
        AuthorityField = new javax.swing.JTextField();
        SpeedField = new javax.swing.JTextField();
        MaxCapacityField = new javax.swing.JTextField();
        CurrentCapacityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        StatusField = new javax.swing.JTextField();
        AdditionalInfoPanel2 = new javax.swing.JPanel();
        TrainShutdownButton = new javax.swing.JButton();
        TrackShutdownButton = new javax.swing.JButton();
        DispatchControlPanel = new javax.swing.JPanel();
        DispatchButton = new javax.swing.JButton();
        SystemInformationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TimeField = new javax.swing.JTextField();
        RushHourField = new javax.swing.JTextField();
        ThroughputField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SelectOperationMode2 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 651));

        MapPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Map"));
        MapPanel2.setLayout(new java.awt.GridBagLayout());

        MapImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MapImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rogueone/images/layout_small.jpg")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        MapPanel2.add(MapImage2, gridBagConstraints);

        BrowserPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Browser"));

        jPanel19.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel19ComponentShown(evt);
            }
        });

        jLabel63.setText("Train Line");

        TrainLineSelect2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Red" }));
        TrainLineSelect2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrainLineSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainLineSelect2ActionPerformed(evt);
            }
        });

        jLabel64.setText("Trains");

        TrainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(254), "D:2",  new Boolean(true)},
                { new Integer(1190), "G:3",  new Boolean(true)},
                { new Integer(52), "G:9", null},
                { new Integer(2955), "M:1",  new Boolean(true)},
                { new Integer(842), "M:10",  new Boolean(true)},
                { new Integer(7922), "Q:3",  new Boolean(true)},
                { new Integer(103), "S:7",  new Boolean(true)},
                { new Integer(8311), "T:2",  new Boolean(true)},
                { new Integer(91), "V:9",  new Boolean(true)},
                { new Integer(1294), "X:7", null},
                { new Integer(399), "Z:2",  new Boolean(true)}
            },
            new String [] {
                "Train", "Position", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TrainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrainTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(TrainTable);

        ChangeParametersButton3.setText("CHANGE ");
        ChangeParametersButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeParametersButton3ActionPerformed(evt);
            }
        });

        jLabel88.setText("Set Parameters");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TrainLineSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel88))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ChangeParametersButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(TrainLineSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel88)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeParametersButton3)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        BrowserPanel2.addTab("Trains", jPanel19);

        jPanel20.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel20ComponentShown(evt);
            }
        });

        jLabel65.setText("Train Line");

        TrainLineBlockSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Red" }));
        TrainLineBlockSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainLineBlockSelectActionPerformed(evt);
            }
        });

        jLabel66.setText("Blocks");

        BlockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A",  new Integer(1),  new Boolean(true)},
                {"A",  new Integer(2),  new Boolean(false)},
                {"A",  new Integer(3),  new Boolean(true)},
                {"B",  new Integer(1),  new Boolean(true)},
                {"B",  new Integer(2),  new Boolean(true)},
                {"B",  new Integer(3),  new Boolean(false)},
                {"B",  new Integer(4),  new Boolean(true)},
                {"B",  new Integer(5),  new Boolean(true)},
                {"C",  new Integer(1),  new Boolean(true)},
                {"C",  new Integer(2),  new Boolean(true)},
                {"C",  new Integer(3),  new Boolean(true)},
                {"C",  new Integer(4),  new Boolean(true)},
                {"D",  new Integer(1),  new Boolean(true)},
                {"D",  new Integer(2),  new Boolean(true)},
                {"D",  new Integer(3),  new Boolean(true)}
            },
            new String [] {
                "Section", "Block", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BlockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(BlockTable);
        if (BlockTable.getColumnModel().getColumnCount() > 0) {
            BlockTable.getColumnModel().getColumn(0).setResizable(false);
            BlockTable.getColumnModel().getColumn(1).setResizable(false);
            BlockTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(TrainLineBlockSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrainLineBlockSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        BrowserPanel2.addTab("Blocks", jPanel20);

        FailureTable.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        FailureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Green", "A",  new Integer(2), "Power"},
                {"Green", "B",  new Integer(3), "Power"},
                {"Red", "F",  new Integer(2), "Broken Rail"}
            },
            new String [] {
                "Track", "Section", "Block", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FailureTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FailureTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(FailureTable);
        if (FailureTable.getColumnModel().getColumnCount() > 0) {
            FailureTable.getColumnModel().getColumn(0).setResizable(false);
            FailureTable.getColumnModel().getColumn(1).setResizable(false);
            FailureTable.getColumnModel().getColumn(2).setResizable(false);
            FailureTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        BrowserPanel2.addTab("Failures", jPanel21);

        InformationPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        InformationPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel67.setText("Train Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 12, 0, 0);
        InformationPanel2.add(jLabel67, gridBagConstraints);

        jLabel68.setText("Current Line");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        InformationPanel2.add(jLabel68, gridBagConstraints);

        jLabel69.setText("Current Section");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        InformationPanel2.add(jLabel69, gridBagConstraints);

        jLabel70.setText("Current Block");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        InformationPanel2.add(jLabel70, gridBagConstraints);

        jLabel71.setText("Speed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        InformationPanel2.add(jLabel71, gridBagConstraints);

        jLabel72.setText("Authority");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 12, 0, 0);
        InformationPanel2.add(jLabel72, gridBagConstraints);

        jLabel74.setText("Current Capacity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        InformationPanel2.add(jLabel74, gridBagConstraints);

        InformationHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        InformationHeader2.setText("Selected Train Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 0, 0);
        InformationPanel2.add(InformationHeader2, gridBagConstraints);

        jLabel75.setText("Max Capacity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        InformationPanel2.add(jLabel75, gridBagConstraints);

        TrainSpeedLabel2.setText("mph");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        InformationPanel2.add(TrainSpeedLabel2, gridBagConstraints);

        TrainAuthorityLabel2.setText("ft");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 6, 0, 0);
        InformationPanel2.add(TrainAuthorityLabel2, gridBagConstraints);

        TrainNameField.setText("254");
        TrainNameField.setMinimumSize(new java.awt.Dimension(10, 30));
        TrainNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        InformationPanel2.add(TrainNameField, gridBagConstraints);

        CurrentLineField.setText("Green");
        CurrentLineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentLineFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        InformationPanel2.add(CurrentLineField, gridBagConstraints);

        CurrentBlockField.setText("4");
        CurrentBlockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentBlockFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        InformationPanel2.add(CurrentBlockField, gridBagConstraints);

        CurrentSectionField.setText("B");
        CurrentSectionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentSectionFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        InformationPanel2.add(CurrentSectionField, gridBagConstraints);

        AuthorityField.setText("1542");
        AuthorityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorityFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        InformationPanel2.add(AuthorityField, gridBagConstraints);

        SpeedField.setText("23.2");
        SpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        InformationPanel2.add(SpeedField, gridBagConstraints);

        MaxCapacityField.setText("125");
        MaxCapacityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxCapacityFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        InformationPanel2.add(MaxCapacityField, gridBagConstraints);

        CurrentCapacityField.setText("50");
        CurrentCapacityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentCapacityFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        InformationPanel2.add(CurrentCapacityField, gridBagConstraints);

        jLabel5.setText("people");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 18);
        InformationPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("people");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 18);
        InformationPanel2.add(jLabel6, gridBagConstraints);

        jLabel76.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        InformationPanel2.add(jLabel76, gridBagConstraints);

        StatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 19, 18);
        InformationPanel2.add(StatusField, gridBagConstraints);

        AdditionalInfoPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Component Disable"));

        TrainShutdownButton.setText("Train Shutdown");
        TrainShutdownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainShutdownButtonActionPerformed(evt);
            }
        });

        TrackShutdownButton.setText("Track Shutdown");
        TrackShutdownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackShutdownButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdditionalInfoPanel2Layout = new javax.swing.GroupLayout(AdditionalInfoPanel2);
        AdditionalInfoPanel2.setLayout(AdditionalInfoPanel2Layout);
        AdditionalInfoPanel2Layout.setHorizontalGroup(
            AdditionalInfoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditionalInfoPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdditionalInfoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrackShutdownButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(TrainShutdownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AdditionalInfoPanel2Layout.setVerticalGroup(
            AdditionalInfoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditionalInfoPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TrainShutdownButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrackShutdownButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DispatchControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dispatch Control"));

        DispatchButton.setText("Dispatch New Train");
        DispatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispatchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DispatchControlPanelLayout = new javax.swing.GroupLayout(DispatchControlPanel);
        DispatchControlPanel.setLayout(DispatchControlPanelLayout);
        DispatchControlPanelLayout.setHorizontalGroup(
            DispatchControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DispatchControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DispatchButton)
                .addContainerGap())
        );
        DispatchControlPanelLayout.setVerticalGroup(
            DispatchControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DispatchControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DispatchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SystemInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("System Information"));

        jLabel2.setText("Time");

        jLabel3.setText("Rush Hour");

        jLabel4.setText("Throughput");

        TimeField.setText("12:31");
        TimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeFieldActionPerformed(evt);
            }
        });

        RushHourField.setText("YES");
        RushHourField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RushHourFieldActionPerformed(evt);
            }
        });

        ThroughputField.setText("1203");
        ThroughputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThroughputFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("p/hr");

        jLabel7.setText("PM");

        javax.swing.GroupLayout SystemInformationPanelLayout = new javax.swing.GroupLayout(SystemInformationPanel);
        SystemInformationPanel.setLayout(SystemInformationPanelLayout);
        SystemInformationPanelLayout.setHorizontalGroup(
            SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SystemInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SystemInformationPanelLayout.createSequentialGroup()
                        .addComponent(ThroughputField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(SystemInformationPanelLayout.createSequentialGroup()
                        .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(RushHourField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SystemInformationPanelLayout.setVerticalGroup(
            SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SystemInformationPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RushHourField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SystemInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ThroughputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation Mode"));

        SelectOperationMode2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic" }));
        SelectOperationMode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectOperationMode2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectOperationMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SelectOperationMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MapPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdditionalInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InformationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DispatchControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SystemInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BrowserPanel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BrowserPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DispatchControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SystemInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(InformationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MapPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdditionalInfoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TrainLineSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainLineSelect2ActionPerformed
        if (TrainLineSelect2.getSelectedIndex() == 0) {
            CurrentLineField.setText("Green");
        }
        else {
            CurrentLineField.setText("Red");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_TrainLineSelect2ActionPerformed

    private void jPanel19ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel19ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel19ComponentShown

    private void TrainLineBlockSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainLineBlockSelectActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_TrainLineBlockSelectActionPerformed

    private void jPanel20ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel20ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20ComponentShown

    private void SelectOperationMode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectOperationMode2ActionPerformed
        if (SelectOperationMode2.getSelectedIndex() == 0) {
            ChangeParametersButton3.setEnabled(true);
            DispatchButton.setEnabled(true);
            TrainShutdownButton.setEnabled(true);
            TrackShutdownButton.setEnabled(true);
        }       // TODO add your handling code here:
        else {
            ChangeParametersButton3.setEnabled(false);
            DispatchButton.setEnabled(false);
            TrainShutdownButton.setEnabled(false);
            TrackShutdownButton.setEnabled(false);
        }
    }//GEN-LAST:event_SelectOperationMode2ActionPerformed

    private void ThroughputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThroughputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThroughputFieldActionPerformed

    private void TimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeFieldActionPerformed
        //check for rushhour
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeFieldActionPerformed

    private void CurrentLineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentLineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentLineFieldActionPerformed

    private void CurrentBlockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentBlockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentBlockFieldActionPerformed

    private void CurrentSectionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentSectionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentSectionFieldActionPerformed

    private void AuthorityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorityFieldActionPerformed

    private void SpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedFieldActionPerformed

    private void MaxCapacityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxCapacityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxCapacityFieldActionPerformed

    private void CurrentCapacityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentCapacityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentCapacityFieldActionPerformed

    private void RushHourFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RushHourFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RushHourFieldActionPerformed

    private void ChangeParametersButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeParametersButton3ActionPerformed
        //get trainID from selected row first column
        ChangeParametersGUI params = new ChangeParametersGUI(trainID);
        params.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeParametersButton3ActionPerformed

    private void TrackShutdownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackShutdownButtonActionPerformed
        TrackShutdownGUI trackShutdown = new TrackShutdownGUI();
        trackShutdown.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_TrackShutdownButtonActionPerformed

    private void TrainShutdownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainShutdownButtonActionPerformed
        TrainShutdownGUI trainShutdown = new TrainShutdownGUI();
        trainShutdown.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_TrainShutdownButtonActionPerformed

    private void TrainNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainNameFieldActionPerformed
        
    }//GEN-LAST:event_TrainNameFieldActionPerformed

    private void DispatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispatchButtonActionPerformed
        DispatchTrainGUI trainDispatch = new DispatchTrainGUI();
        trainDispatch.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_DispatchButtonActionPerformed

    private void TrainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrainTableMouseClicked
        
        InformationHeader2.setText("Selected Train Information");

        jLabel67.setText("Train Name");
        jLabel68.setText("Current Line");
        jLabel69.setText("Current Section");
        jLabel70.setText("Current Blcok");
        jLabel71.setText("Speed");
        jLabel72.setText("Authority");
        jLabel74.setText("Current Capacity");
        jLabel75.setText("Max Capacity");
        jLabel76.setText("Status");

        
        TrainSpeedLabel2.setText("mph");
        TrainAuthorityLabel2.setText("feet");
        jLabel5.setText("people");
        jLabel6.setText("people");
        
        SpeedField.setVisible(true);
        AuthorityField.setVisible(true);
        CurrentCapacityField.setVisible(true);
        MaxCapacityField.setVisible(true);
        StatusField.setVisible(true);
        
        if (TrainLineBlockSelect.getSelectedIndex() == 0) {
            CurrentLineField.setText("Green");
        }
        else {
            CurrentLineField.setText("Red");
        }
        
        
        if ( evt.getClickCount() == 1){
            JTable table = (JTable)evt.getSource();
            int row = table.getSelectedRow();
            trainID = (int)table.getValueAt(row, 0);
            //global to program
            
            //parse position field
            
            String position = (String)table.getValueAt(row, 1);
            String[] parts = position.split(":");
            String partSection = parts[0]; 
            String partBlock = parts[1];
            Object booleanStatus = table.getValueAt(row, 2);
            if (booleanStatus == null){
                StatusField.setText("Disabled");
            }
            else {
                StatusField.setText("Operational");
            }
            
            CurrentSectionField.setText(partSection);
            CurrentBlockField.setText(partBlock);
            TrainNameField.setText(Integer.toString(trainID));
            
            if (SelectOperationMode2.getSelectedIndex() == 1){
                ChangeParametersButton3.setEnabled(false);
            }
            else { 
                ChangeParametersButton3.setEnabled(true);
            }
        }
        
        if ( evt.getClickCount() == 2){
            //double mouse click calls Train Model CreateGUIObject to dispalay IDed train model
            JTable table = (JTable)evt.getSource();
            int row = table.getSelectedRow();
            trainID = (int)table.getValueAt(row, 0);
            
            //TrainHandler.CreateGUIObject(trainID);
        }
        
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_TrainTableMouseClicked

    private void StatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusFieldActionPerformed

    private void BlockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockTableMouseClicked
        //set up screen for Block Info
        
        InformationHeader2.setText("Selected Block Information");
        jLabel67.setText("Block Section");
        jLabel68.setText("Block Line");
        jLabel69.setText("Block Number");
        jLabel70.setText("Block Length");
        jLabel71.setText("Block Speed");
        jLabel72.setText("Station");
        jLabel74.setText("Crossing");
        jLabel75.setText("Underground");
        jLabel76.setText("Status");
        
        TrainSpeedLabel2.setText("mph");
        TrainAuthorityLabel2.setText("feet");
        jLabel5.setText("");
        jLabel6.setText("");
        
        TrainSpeedLabel2.setText("");
        TrainAuthorityLabel2.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        
        SpeedField.setVisible(true);
        AuthorityField.setVisible(true);
        CurrentCapacityField.setVisible(true);
        MaxCapacityField.setVisible(true);
        StatusField.setVisible(true);
        
        if (TrainLineBlockSelect.getSelectedIndex() == 0) {
            CurrentLineField.setText("Green");
        }
        else {
            CurrentLineField.setText("Red");
        }

        
        if (evt.getClickCount() == 1){
            JTable blockTable = (JTable)evt.getSource();
            int row = blockTable.getSelectedRow();
            String blockSection = (String)blockTable.getValueAt(row, 0);
            int blockNumber = (int)blockTable.getValueAt(row, 1);
            
            TrainNameField.setText(blockSection);
            CurrentSectionField.setText(Integer.toString(blockNumber));
            
            Object booleanBlockStatus = blockTable.getValueAt(row, 2);
            if (booleanBlockStatus == null){
                StatusField.setText("Disabled");
            }
            else {
                StatusField.setText("Operational");
            }
            
        }
        
        if (evt.getClickCount() == 2){
        }



// TODO add your handling code here:
    }//GEN-LAST:event_BlockTableMouseClicked

    private void FailureTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FailureTableMouseClicked
        InformationHeader2.setText("Selected Failure Information");
        
        jLabel67.setText("Failure Type");
        jLabel68.setText("Failure Line");
        jLabel69.setText("Failure Block");
        jLabel70.setText("Failure Section");
        jLabel71.setText("");
        jLabel72.setText("");
        jLabel74.setText("");
        jLabel75.setText("");
        jLabel76.setText("");
        TrainSpeedLabel2.setText("");
        TrainAuthorityLabel2.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        
        
        SpeedField.setVisible(false);
        AuthorityField.setVisible(false);
        CurrentCapacityField.setVisible(false);
        MaxCapacityField.setVisible(false);
        StatusField.setVisible(false);
        
        if (evt.getClickCount() == 1){
            JTable failureTable = (JTable)evt.getSource();
            int row = failureTable.getSelectedRow();
            String failureLine = (String)failureTable.getValueAt(row, 0);
            String failureSection = (String)failureTable.getValueAt(row, 1);
            int failureBlock = (int)failureTable.getValueAt(row, 2);
            String failureType = (String)failureTable.getValueAt(row, 3);
            
            TrainNameField.setText(failureType);
            CurrentLineField.setText(failureLine);
            CurrentSectionField.setText(failureSection);
            CurrentBlockField.setText(Integer.toString(failureBlock));
            
        }
        
        if (evt.getClickCount() == 2){
            
        }
            
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_FailureTableMouseClicked

//    private void UpdateTableInformation(java.awt.event.ActionEvent evt){
//        int selectedRowIndex = TrainTable.getSelectedRow();
//        String TrainID = TrainTable.getModel().getValueAt(selectedRowIndex, 0).toString(); 
//        TrainNameField.setText(TrainID);// TODO add your handling code here:
//    }
    
    /**
     *
     */
    public void InitializeGUIObject(){
        TrainNameField.setText("");
        CurrentLineField.setText("");
        CurrentBlockField.setText("0");
        CurrentSectionField.setText("");
        SpeedField.setText("0.00");
        AuthorityField.setText("0.00");
        CurrentCapacityField.setText("");
        MaxCapacityField.setText("");
        ThroughputField.setText("");
        StatusField.setText("");
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdditionalInfoPanel2;
    private javax.swing.JTextField AuthorityField;
    private javax.swing.JTable BlockTable;
    private javax.swing.JTabbedPane BrowserPanel2;
    private javax.swing.JButton ChangeParametersButton3;
    private javax.swing.JTextField CurrentBlockField;
    private javax.swing.JTextField CurrentCapacityField;
    private javax.swing.JTextField CurrentLineField;
    private javax.swing.JTextField CurrentSectionField;
    private javax.swing.JButton DispatchButton;
    private javax.swing.JPanel DispatchControlPanel;
    private javax.swing.JTable FailureTable;
    private javax.swing.JLabel InformationHeader2;
    private javax.swing.JPanel InformationPanel2;
    private javax.swing.JLabel MapImage2;
    private javax.swing.JPanel MapPanel2;
    private javax.swing.JTextField MaxCapacityField;
    private javax.swing.JTextField RushHourField;
    private javax.swing.JComboBox<String> SelectOperationMode2;
    private javax.swing.JTextField SpeedField;
    private javax.swing.JTextField StatusField;
    private javax.swing.JPanel SystemInformationPanel;
    private javax.swing.JTextField ThroughputField;
    private javax.swing.JTextField TimeField;
    private javax.swing.JButton TrackShutdownButton;
    private javax.swing.JLabel TrainAuthorityLabel2;
    private javax.swing.JComboBox<String> TrainLineBlockSelect;
    private javax.swing.JComboBox<String> TrainLineSelect2;
    private javax.swing.JTextField TrainNameField;
    private javax.swing.JButton TrainShutdownButton;
    private javax.swing.JLabel TrainSpeedLabel2;
    private javax.swing.JTable TrainTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
